import "./globals.css";
import { Inter } from "next/font/google";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <script
          rel="preload"
          href="https://kit.fontawesome.com/6a7826155f.js"
          as="script"
          crossorigin="use-credentials"></script>
      </head>
      <body className={inter.className}>{children}</body>
    </html>
  );
}
